post:
  summary: Reload interface configurations
  tags:
    - control
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../schemas/ConfigUpdateResponse.yaml'
