get:
  summary: Get interface configuration
  tags:
  - control
  operationId: getConfigurationByIface
  parameters:
      - in: path
        name: interface
        schema:
          type: string
          example: eth0
        required: true
        description: The interface to get the configuration for
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../schemas/configresponse.yaml'
