# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  - push
  - pull_request

jobs:

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build for AMD64
      run: GOOS=linux GOARCH=amd64 go build -v -a -x ./...

    - name: Test
      run: |
        go test -v ./... -covermode=atomic -coverprofile=coverage.out
        go tool cover -func=coverage.out -o=coverage.out

    - name: Race Detector
      run: |
        go test -race -v ./...
