type: object
allOf:
  - $ref: './response.yaml'
properties:
  ifaces:
    type: object
    additionalProperties:
      $ref: './CaptureConfig.yaml'
    example:
      eth0:
        promisc: true
        ring_buffer:
          num_blocks: 4
          block_size: 1048576

