type: object
properties:
  block_size:
    type: integer
    description: Specifies the size of a block, which defines how many packets can be held within a block.
    example: 1048576
  num_blocks:
    type: integer
    description: Guides how many blocks are part of the ring buffer.
    example: 4
